# Generated by Django 4.1.5 on 2023-02-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0004_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.CharField(max_length=100000),
        ),
    ]
